# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

# # Use a package of configuration called an orb, see https://circleci.com/docs/2.0/orb-intro/
# orbs:
#   # Declare a dependency on the welcome-orb
#   welcome: circleci/welcome-orb@0.3.1

executors:
  ubuntu:
    machine:
      image: ubuntu-1604:201903-01

commands:
  install_lua:
    description: "Installs lua"
    parameters:
      to:
        type: string
        default: "Hello World"
    steps:
      - run: echo << parameters.to >>
  install_luarocks:
    description: "Installs luarocks"
    steps:
      - run:
          name: "install lua"
          command: | 
            wget https://luarocks.org/releases/luarocks-3.1.3.tar.gz
            tar zxpf luarocks-3.1.3.tar.gz
            cd luarocks-3.1.3
            ./configure; sudo make bootstrap
            sudo luarocks install luasocket
            lua
            echo "finished"


jobs:
  build:
    executor: ubuntu
    steps:
      - checkout
      - install_lua
      - install_luarocks

# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  # Name the workflow "Welcome"
  verify_and_build:
    # Run the welcome/run job in its own container
    jobs:
      - build
