# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

# # Use a package of configuration called an orb, see https://circleci.com/docs/2.0/orb-intro/
# orbs:
#   # Declare a dependency on the welcome-orb
#   welcome: circleci/welcome-orb@0.3.1

executors:
  ubuntu:
    machine:
      image: ubuntu-1604:201903-01

commands:
  install_lua:
    description: "Installs lua"
    steps:
      - run:
          name: "Install Lua"
          command: |
            sudo apt install lua5.3	
            sudo apt-get install liblua5.2-dev

  install_luarocks:
    description: "Installs luarocks"
    steps:
      - run:
          name: "Install luarocks"
          command: |
            sudo apt-get update
            sudo apt-get install luarocks
            luarocks --version

  luacheck:
    description: "Run luacheck"
    # parameters:
    # TODO: parameterise the luacheck target (src atm)
    steps:
      - run:
          name: "Install luacheck"
          command: |
            sudo luarocks install luacheck
      - run:
          name: "luacheck"
          command: |
            sudo luacheck src

  unit_test:
    description: "Run unit tests"
    steps:
      - run:
          name: "run tests"
          command: |
            cd tests
            ./run.sh

  build_binaries:
    description: "Build and save binary distributable"
    steps:
      - run:
          name: "install love-release"
          command: |
            sudo luarocks install love-release
      - run:
          name: "build .love"
          command: |
            mkdir build;
            cp src -r build;
            cp libs -r build;
            cp resources -r build;
            cp main.lua build;
            cp conf.lua build;
            cd build;
            love-release -D -W 32 -M;
            ls;
            # zip -9 -r grim-gamers.love .
      - store_artifacts:
          path: build
          # destination: grim-gamers.love

jobs:
  validate_and_test:
    executor: ubuntu
    steps:
      - checkout
      - install_lua
      - install_luarocks
      - luacheck
      - unit_test
      - build_binaries

# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  validate_and_build:
    jobs:
      - validate_and_test
