return {
    DEBUG = {
        ENABLE_LIGHTING = true
    },
    COLOURS = {
        WHITE_TORCHLIGHT = {230 / 255, 197 / 255, 143 / 255}, --#e6c58f
        ORANGE_TORCHLIGHT = {255 / 255, 141 / 255, 51 / 255} -- #ff8d33
    },
    WALK_ACCELERATION = 75,
    WALK_MAX_SPEED = 255,
    AIRCONTROL_ACCELERATION = 12,
    AIRCONTROL_MAX_SPEED = 200,
    FRICTION = 1450,
    JUMP_ACCELERATION = 540,
    JUMP_MULTIPLIER = 4,
    JUMP_SMALL_MULTIPLIER = 10,
    GRAVITY = 4,
    GRAVITY_DECELERATION = 400,
    PLAYER_HEIGHT = 18,
    PLAYER_WIDTH = 22,
    PLAYER_TERMINAL_VELOCITY = 300,
    PLAYER_FALLSPEED_MODIFIER = 1.2,
    PLAYER_AIR_TO_GROUND_MOMENTUM_CONSERVATION_RATIO = 0.25,
    PLAYER_GROUND_TO_AIR_MOMENTUM_CONSERVATION_RATIO = 1.15,
    PLAYER_WALK_OFF_LEDGE_MOMENTUM_CONSERVATION_RATIO = 1.0,
    PLAYER_LIGHT_SOURCE_RADIUS = 120,
    STATIC_LIGHT_SOURCE_RADIUS = 100,
    ITEM_LIGHT_SOURCE_RADIUS = 20,
    ITEM_HEIGHT = 20,
    ITEM_WIDTH = 20,
    Y_OFFSET_TO_TEST_PLAYER_IS_GROUNDED = 1.0001,
    WORLD_SCALE = 1,
    TILE_WIDTH = 32,
    TILE_HEIGHT = 32,
    CAMERA_DAMPENING = 15,
    WINDOWED_RESOLUTION = {x = 1280, y = 720},
    DEFAULT_INVENTORY_SIZE = 30
}
